server:
  port: 6666

spring:
  activemq:
    broker-url: tcp://192.168.1.203:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true # false = queue   true = topic

#自定义队列名称
mytopic: boot-activemq-topic
